// Auto-generated by scripts/generate-registry.js
// Do not edit this file manually - run the generator instead

import { ServiceBusinessMap } from './map-service-business.types';

// Business-Service Imports
import * as b2bServicesasoServices from './data/b2b-services/aso-services';
import * as b2bServices360DigitalMarketing from './data/b2b-services/360-digital-marketing';
import * as b2bServicesecommerceMarketing from './data/b2b-services/ecommerce-marketing';
import * as b2bServicesgmbServices from './data/b2b-services/gmb-services';
import * as b2bServicesgoogleAds from './data/b2b-services/google-ads';
import * as b2bServicesleadsGeneration from './data/b2b-services/leads-generation';
import * as b2bServiceslocalSeo from './data/b2b-services/local-seo';
// import * as b2bServicesmarketingAutomation from './data/b2b-services/marketing-automation';
import * as b2bServicesmetaAds from './data/b2b-services/meta-ads';
import * as b2bServicesmobileAppsDevelopment from './data/b2b-services/mobile-apps-development';
import * as b2bServicesotherAds from './data/b2b-services/other-ads';
import * as b2bServicesseoServices from './data/b2b-services/seo-services';
import * as b2bServicessocialMediaMarketing from './data/b2b-services/social-media-marketing';
import * as b2bServiceswebDesignDevelopment from './data/b2b-services/web-design-development';
import * as b2bServiceswebsiteMaintenance from './data/b2b-services/website-maintenance';
import * as b2cServicesasoServices from './data/b2c-services/aso-services';
import * as b2cServices360DigitalMarketing from './data/b2c-services/360-digital-marketing';
import * as b2cServicesecommerceMarketing from './data/b2c-services/ecommerce-marketing';
import * as b2cServicesgmbServices from './data/b2c-services/gmb-services';
import * as b2cServicesgoogleAds from './data/b2c-services/google-ads';
import * as b2cServicesleadsGeneration from './data/b2c-services/leads-generation';
import * as b2cServiceslocalSeo from './data/b2c-services/local-seo';
// import * as b2cServicesmarketingAutomation from './data/b2c-services/marketing-automation';
import * as b2cServicesmetaAds from './data/b2c-services/meta-ads';
import * as b2cServicesmobileAppsDevelopment from './data/b2c-services/mobile-apps-development';
import * as b2cServicesotherAds from './data/b2c-services/other-ads';
import * as b2cServicesseoServices from './data/b2c-services/seo-services';
import * as b2cServicessocialMediaMarketing from './data/b2c-services/social-media-marketing';
import * as b2cServiceswebDesignDevelopment from './data/b2c-services/web-design-development';
import * as b2cServiceswebsiteMaintenance from './data/b2c-services/website-maintenance';
import * as consultantsasoServices from './data/consultants/aso-services';
import * as consultants360DigitalMarketing from './data/consultants/360-digital-marketing';
import * as consultantsecommerceMarketing from './data/consultants/ecommerce-marketing';
import * as consultantsgmbServices from './data/consultants/gmb-services';
import * as consultantsgoogleAds from './data/consultants/google-ads';
import * as consultantsleadsGeneration from './data/consultants/leads-generation';
import * as consultantslocalSeo from './data/consultants/local-seo';
// import * as consultantsmarketingAutomation from './data/consultants/marketing-automation';
import * as consultantsmetaAds from './data/consultants/meta-ads';
import * as consultantsmobileAppsDevelopment from './data/consultants/mobile-apps-development';
import * as consultantsotherAds from './data/consultants/other-ads';
import * as consultantsseoServices from './data/consultants/seo-services';
import * as consultantssocialMediaMarketing from './data/consultants/social-media-marketing';
import * as consultantswebDesignDevelopment from './data/consultants/web-design-development';
import * as consultantswebsiteMaintenance from './data/consultants/website-maintenance';
import * as doctorsClinicsasoServices from './data/doctors-clinics/aso-services';
import * as doctorsClinics360DigitalMarketing from './data/doctors-clinics/360-digital-marketing';
import * as doctorsClinicsecommerceMarketing from './data/doctors-clinics/ecommerce-marketing';
import * as doctorsClinicsgmbServices from './data/doctors-clinics/gmb-services';
import * as doctorsClinicsgoogleAds from './data/doctors-clinics/google-ads';
import * as doctorsClinicsleadsGeneration from './data/doctors-clinics/leads-generation';
import * as doctorsClinicslocalSeo from './data/doctors-clinics/local-seo';
// import * as doctorsClinicsmarketingAutomation from './data/doctors-clinics/marketing-automation';
import * as doctorsClinicsmetaAds from './data/doctors-clinics/meta-ads';
import * as doctorsClinicsmobileAppsDevelopment from './data/doctors-clinics/mobile-apps-development';
import * as doctorsClinicsotherAds from './data/doctors-clinics/other-ads';
import * as doctorsClinicsseoServices from './data/doctors-clinics/seo-services';
import * as doctorsClinicssocialMediaMarketing from './data/doctors-clinics/social-media-marketing';
import * as doctorsClinicswebDesignDevelopment from './data/doctors-clinics/web-design-development';
import * as doctorsClinicswebsiteMaintenance from './data/doctors-clinics/website-maintenance';
import * as eCommerceBrandsasoServices from './data/e-commerce-brands/aso-services';
import * as eCommerceBrands360DigitalMarketing from './data/e-commerce-brands/360-digital-marketing';
import * as eCommerceBrandsecommerceMarketing from './data/e-commerce-brands/ecommerce-marketing';
import * as eCommerceBrandsgmbServices from './data/e-commerce-brands/gmb-services';
import * as eCommerceBrandsgoogleAds from './data/e-commerce-brands/google-ads';
import * as eCommerceBrandsleadsGeneration from './data/e-commerce-brands/leads-generation';
import * as eCommerceBrandslocalSeo from './data/e-commerce-brands/local-seo';
// import * as eCommerceBrandsmarketingAutomation from './data/e-commerce-brands/marketing-automation';
import * as eCommerceBrandsmetaAds from './data/e-commerce-brands/meta-ads';
import * as eCommerceBrandsmobileAppsDevelopment from './data/e-commerce-brands/mobile-apps-development';
import * as eCommerceBrandsotherAds from './data/e-commerce-brands/other-ads';
import * as eCommerceBrandsseoServices from './data/e-commerce-brands/seo-services';
import * as eCommerceBrandssocialMediaMarketing from './data/e-commerce-brands/social-media-marketing';
import * as eCommerceBrandswebDesignDevelopment from './data/e-commerce-brands/web-design-development';
import * as eCommerceBrandswebsiteMaintenance from './data/e-commerce-brands/website-maintenance';
import * as educationalInstitutionsasoServices from './data/educational-institutions/aso-services';
import * as educationalInstitutions360DigitalMarketing from './data/educational-institutions/360-digital-marketing';
import * as educationalInstitutionsecommerceMarketing from './data/educational-institutions/ecommerce-marketing';
import * as educationalInstitutionsgmbServices from './data/educational-institutions/gmb-services';
import * as educationalInstitutionsgoogleAds from './data/educational-institutions/google-ads';
import * as educationalInstitutionsleadsGeneration from './data/educational-institutions/leads-generation';
import * as educationalInstitutionslocalSeo from './data/educational-institutions/local-seo';
// import * as educationalInstitutionsmarketingAutomation from './data/educational-institutions/marketing-automation';
import * as educationalInstitutionsmetaAds from './data/educational-institutions/meta-ads';
import * as educationalInstitutionsmobileAppsDevelopment from './data/educational-institutions/mobile-apps-development';
import * as educationalInstitutionsotherAds from './data/educational-institutions/other-ads';
import * as educationalInstitutionsseoServices from './data/educational-institutions/seo-services';
import * as educationalInstitutionssocialMediaMarketing from './data/educational-institutions/social-media-marketing';
import * as educationalInstitutionswebDesignDevelopment from './data/educational-institutions/web-design-development';
import * as educationalInstitutionswebsiteMaintenance from './data/educational-institutions/website-maintenance';
import * as fashionBrandsasoServices from './data/fashion-brands/aso-services';
import * as fashionBrands360DigitalMarketing from './data/fashion-brands/360-digital-marketing';
import * as fashionBrandsecommerceMarketing from './data/fashion-brands/ecommerce-marketing';
import * as fashionBrandsgmbServices from './data/fashion-brands/gmb-services';
import * as fashionBrandsgoogleAds from './data/fashion-brands/google-ads';
import * as fashionBrandsleadsGeneration from './data/fashion-brands/leads-generation';
import * as fashionBrandslocalSeo from './data/fashion-brands/local-seo';
// import * as fashionBrandsmarketingAutomation from './data/fashion-brands/marketing-automation';
import * as fashionBrandsmetaAds from './data/fashion-brands/meta-ads';
import * as fashionBrandsmobileAppsDevelopment from './data/fashion-brands/mobile-apps-development';
import * as fashionBrandsotherAds from './data/fashion-brands/other-ads';
import * as fashionBrandsseoServices from './data/fashion-brands/seo-services';
import * as fashionBrandssocialMediaMarketing from './data/fashion-brands/social-media-marketing';
import * as fashionBrandswebDesignDevelopment from './data/fashion-brands/web-design-development';
import * as fashionBrandswebsiteMaintenance from './data/fashion-brands/website-maintenance';
import * as gymsFitnessasoServices from './data/gyms-fitness/aso-services';
import * as gymsFitness360DigitalMarketing from './data/gyms-fitness/360-digital-marketing';
import * as gymsFitnessecommerceMarketing from './data/gyms-fitness/ecommerce-marketing';
import * as gymsFitnessgmbServices from './data/gyms-fitness/gmb-services';
import * as gymsFitnessgoogleAds from './data/gyms-fitness/google-ads';
import * as gymsFitnessleadsGeneration from './data/gyms-fitness/leads-generation';
import * as gymsFitnesslocalSeo from './data/gyms-fitness/local-seo';
// import * as gymsFitnessmarketingAutomation from './data/gyms-fitness/marketing-automation';
import * as gymsFitnessmetaAds from './data/gyms-fitness/meta-ads';
import * as gymsFitnessmobileAppsDevelopment from './data/gyms-fitness/mobile-apps-development';
import * as gymsFitnessotherAds from './data/gyms-fitness/other-ads';
import * as gymsFitnessseoServices from './data/gyms-fitness/seo-services';
import * as gymsFitnesssocialMediaMarketing from './data/gyms-fitness/social-media-marketing';
import * as gymsFitnesswebDesignDevelopment from './data/gyms-fitness/web-design-development';
import * as gymsFitnesswebsiteMaintenance from './data/gyms-fitness/website-maintenance';
import * as hotelResortsasoServices from './data/hotel-resorts/aso-services';
import * as hotelResorts360DigitalMarketing from './data/hotel-resorts/360-digital-marketing';
import * as hotelResortsecommerceMarketing from './data/hotel-resorts/ecommerce-marketing';
import * as hotelResortsgmbServices from './data/hotel-resorts/gmb-services';
import * as hotelResortsgoogleAds from './data/hotel-resorts/google-ads';
import * as hotelResortsleadsGeneration from './data/hotel-resorts/leads-generation';
import * as hotelResortslocalSeo from './data/hotel-resorts/local-seo';
import * as hotelResortsmarketingAutomation from './data/hotel-resorts/marketing-automation';
import * as hotelResortsmetaAds from './data/hotel-resorts/meta-ads';
import * as hotelResortsmobileAppsDevelopment from './data/hotel-resorts/mobile-apps-development';
import * as hotelResortsotherAds from './data/hotel-resorts/other-ads';
import * as hotelResortsseoServices from './data/hotel-resorts/seo-services';
import * as hotelResortssocialMediaMarketing from './data/hotel-resorts/social-media-marketing';
import * as hotelResortswebDesignDevelopment from './data/hotel-resorts/web-design-development';
import * as hotelResortswebsiteMaintenance from './data/hotel-resorts/website-maintenance';
import * as interiorDesignersasoServices from './data/interior-designers/aso-services';
import * as interiorDesigners360DigitalMarketing from './data/interior-designers/360-digital-marketing';
import * as interiorDesignersecommerceMarketing from './data/interior-designers/ecommerce-marketing';
import * as interiorDesignersgmbServices from './data/interior-designers/gmb-services';
import * as interiorDesignersgoogleAds from './data/interior-designers/google-ads';
import * as interiorDesignersleadsGeneration from './data/interior-designers/leads-generation';
import * as interiorDesignerslocalSeo from './data/interior-designers/local-seo';
// import * as interiorDesignersmarketingAutomation from './data/interior-designers/marketing-automation';
import * as interiorDesignersmetaAds from './data/interior-designers/meta-ads';
import * as interiorDesignersmobileAppsDevelopment from './data/interior-designers/mobile-apps-development';
import * as interiorDesignersotherAds from './data/interior-designers/other-ads';
import * as interiorDesignersseoServices from './data/interior-designers/seo-services';
import * as interiorDesignerssocialMediaMarketing from './data/interior-designers/social-media-marketing';
import * as interiorDesignerswebDesignDevelopment from './data/interior-designers/web-design-development';
import * as interiorDesignerswebsiteMaintenance from './data/interior-designers/website-maintenance';
import * as localBusinessesasoServices from './data/local-businesses/aso-services';
import * as localBusinesses360DigitalMarketing from './data/local-businesses/360-digital-marketing';
import * as localBusinessesecommerceMarketing from './data/local-businesses/ecommerce-marketing';
import * as localBusinessesgmbServices from './data/local-businesses/gmb-services';
import * as localBusinessesgoogleAds from './data/local-businesses/google-ads';
import * as localBusinessesleadsGeneration from './data/local-businesses/leads-generation';
import * as localBusinesseslocalSeo from './data/local-businesses/local-seo';
import * as localBusinessesmarketingAutomation from './data/local-businesses/marketing-automation';
import * as localBusinessesmetaAds from './data/local-businesses/meta-ads';
import * as localBusinessesmobileAppsDevelopment from './data/local-businesses/mobile-apps-development';
import * as localBusinessesotherAds from './data/local-businesses/other-ads';
import * as localBusinessesseoServices from './data/local-businesses/seo-services';
import * as localBusinessessocialMediaMarketing from './data/local-businesses/social-media-marketing';
import * as localBusinesseswebDesignDevelopment from './data/local-businesses/web-design-development';
import * as localBusinesseswebsiteMaintenance from './data/local-businesses/website-maintenance';
import * as pharmaCompaniesasoServices from './data/pharma-companies/aso-services';
import * as pharmaCompanies360DigitalMarketing from './data/pharma-companies/360-digital-marketing';
import * as pharmaCompaniesecommerceMarketing from './data/pharma-companies/ecommerce-marketing';
import * as pharmaCompaniesgmbServices from './data/pharma-companies/gmb-services';
import * as pharmaCompaniesgoogleAds from './data/pharma-companies/google-ads';
import * as pharmaCompaniesleadsGeneration from './data/pharma-companies/leads-generation';
import * as pharmaCompanieslocalSeo from './data/pharma-companies/local-seo';
// import * as pharmaCompaniesmarketingAutomation from './data/pharma-companies/marketing-automation';
import * as pharmaCompaniesmetaAds from './data/pharma-companies/meta-ads';
import * as pharmaCompaniesmobileAppsDevelopment from './data/pharma-companies/mobile-apps-development';
import * as pharmaCompaniesotherAds from './data/pharma-companies/other-ads';
import * as pharmaCompaniesseoServices from './data/pharma-companies/seo-services';
import * as pharmaCompaniessocialMediaMarketing from './data/pharma-companies/social-media-marketing';
import * as pharmaCompanieswebDesignDevelopment from './data/pharma-companies/web-design-development';
import * as pharmaCompanieswebsiteMaintenance from './data/pharma-companies/website-maintenance';
import * as realEstateasoServices from './data/real-estate/aso-services';
import * as realEstate360DigitalMarketing from './data/real-estate/360-digital-marketing';
import * as realEstateecommerceMarketing from './data/real-estate/ecommerce-marketing';
import * as realEstategmbServices from './data/real-estate/gmb-services';
import * as realEstategoogleAds from './data/real-estate/google-ads';
import * as realEstateleadsGeneration from './data/real-estate/leads-generation';
import * as realEstatelocalSeo from './data/real-estate/local-seo';
// import * as realEstatemarketingAutomation from './data/real-estate/marketing-automation';
import * as realEstatemetaAds from './data/real-estate/meta-ads';
import * as realEstatemobileAppsDevelopment from './data/real-estate/mobile-apps-development';
import * as realEstateotherAds from './data/real-estate/other-ads';
import * as realEstateseoServices from './data/real-estate/seo-services';
import * as realEstatesocialMediaMarketing from './data/real-estate/social-media-marketing';
import * as realEstatewebDesignDevelopment from './data/real-estate/web-design-development';
import * as realEstatewebsiteMaintenance from './data/real-estate/website-maintenance';
import * as restaurantsCafesasoServices from './data/restaurants-cafes/aso-services';
import * as restaurantsCafes360DigitalMarketing from './data/restaurants-cafes/360-digital-marketing';
// import * as restaurantsCafesecommerceMarketing from './data/restaurants-cafes/ecommerce-marketing';
import * as restaurantsCafesgmbServices from './data/restaurants-cafes/gmb-services';
import * as restaurantsCafesgoogleAds from './data/restaurants-cafes/google-ads';
import * as restaurantsCafesleadsGeneration from './data/restaurants-cafes/leads-generation';
import * as restaurantsCafeslocalSeo from './data/restaurants-cafes/local-seo';
// import * as restaurantsCafesmarketingAutomation from './data/restaurants-cafes/marketing-automation';
import * as restaurantsCafesmetaAds from './data/restaurants-cafes/meta-ads';
import * as restaurantsCafesmobileAppsDevelopment from './data/restaurants-cafes/mobile-apps-development';
import * as restaurantsCafesotherAds from './data/restaurants-cafes/other-ads';
import * as restaurantsCafesseoServices from './data/restaurants-cafes/seo-services';
import * as restaurantsCafessocialMediaMarketing from './data/restaurants-cafes/social-media-marketing';
import * as restaurantsCafeswebDesignDevelopment from './data/restaurants-cafes/web-design-development';
import * as restaurantsCafeswebsiteMaintenance from './data/restaurants-cafes/website-maintenance';
import * as startupsEntrepreneursasoServices from './data/startups-entrepreneurs/aso-services';
import * as startupsEntrepreneurs360DigitalMarketing from './data/startups-entrepreneurs/360-digital-marketing';
// import * as startupsEntrepreneursecommerceMarketing from './data/startups-entrepreneurs/ecommerce-marketing';
import * as startupsEntrepreneursgmbServices from './data/startups-entrepreneurs/gmb-services';
import * as startupsEntrepreneursgoogleAds from './data/startups-entrepreneurs/google-ads';
import * as startupsEntrepreneursleadsGeneration from './data/startups-entrepreneurs/leads-generation';
import * as startupsEntrepreneurslocalSeo from './data/startups-entrepreneurs/local-seo';
// import * as startupsEntrepreneursmarketingAutomation from './data/startups-entrepreneurs/marketing-automation';
import * as startupsEntrepreneursmetaAds from './data/startups-entrepreneurs/meta-ads';
import * as startupsEntrepreneursmobileAppsDevelopment from './data/startups-entrepreneurs/mobile-apps-development';
import * as startupsEntrepreneursotherAds from './data/startups-entrepreneurs/other-ads';
import * as startupsEntrepreneursseoServices from './data/startups-entrepreneurs/seo-services';
import * as startupsEntrepreneurssocialMediaMarketing from './data/startups-entrepreneurs/social-media-marketing';
import * as startupsEntrepreneurswebDesignDevelopment from './data/startups-entrepreneurs/web-design-development';
import * as startupsEntrepreneurswebsiteMaintenance from './data/startups-entrepreneurs/website-maintenance';
import * as travelTourismasoServices from './data/travel-tourism/aso-services';
import * as travelTourism360DigitalMarketing from './data/travel-tourism/360-digital-marketing';
// import * as travelTourismecommerceMarketing from './data/travel-tourism/ecommerce-marketing';
import * as travelTourismgmbServices from './data/travel-tourism/gmb-services';
import * as travelTourismgoogleAds from './data/travel-tourism/google-ads';
import * as travelTourismleadsGeneration from './data/travel-tourism/leads-generation';
import * as travelTourismlocalSeo from './data/travel-tourism/local-seo';
// import * as travelTourismmarketingAutomation from './data/travel-tourism/marketing-automation';
import * as travelTourismmetaAds from './data/travel-tourism/meta-ads';
import * as travelTourismmobileAppsDevelopment from './data/travel-tourism/mobile-apps-development';
import * as travelTourismotherAds from './data/travel-tourism/other-ads';
import * as travelTourismseoServices from './data/travel-tourism/seo-services';
import * as travelTourismsocialMediaMarketing from './data/travel-tourism/social-media-marketing';
import * as travelTourismwebDesignDevelopment from './data/travel-tourism/web-design-development';
import * as travelTourismwebsiteMaintenance from './data/travel-tourism/website-maintenance';

const maps: ServiceBusinessMap[] = [
  b2bServicesasoServices.map,
  b2bServices360DigitalMarketing.map,
  b2bServicesecommerceMarketing.map,
  b2bServicesgmbServices.map,
  b2bServicesgoogleAds.map,
  b2bServicesleadsGeneration.map,
  b2bServiceslocalSeo.map,
  // b2bServicesmarketingAutomation.map,
  b2bServicesmetaAds.map,
  b2bServicesmobileAppsDevelopment.map,
  b2bServicesotherAds.map,
  b2bServicesseoServices.map,
  b2bServicessocialMediaMarketing.map,
  b2bServiceswebDesignDevelopment.map,
  b2bServiceswebsiteMaintenance.map,
  b2cServicesasoServices.map,
  b2cServices360DigitalMarketing.map,
  b2cServicesecommerceMarketing.map,
  b2cServicesgmbServices.map,
  b2cServicesgoogleAds.map,
  b2cServicesleadsGeneration.map,
  b2cServiceslocalSeo.map,
  // b2cServicesmarketingAutomation.map,
  b2cServicesmetaAds.map,
  b2cServicesmobileAppsDevelopment.map,
  b2cServicesotherAds.map,
  b2cServicesseoServices.map,
  b2cServicessocialMediaMarketing.map,
  b2cServiceswebDesignDevelopment.map,
  b2cServiceswebsiteMaintenance.map,
  consultantsasoServices.map,
  consultants360DigitalMarketing.map,
  consultantsecommerceMarketing.map,
  consultantsgmbServices.map,
  consultantsgoogleAds.map,
  consultantsleadsGeneration.map,
  consultantslocalSeo.map,
  // consultantsmarketingAutomation.map,
  consultantsmetaAds.map,
  consultantsmobileAppsDevelopment.map,
  consultantsotherAds.map,
  consultantsseoServices.map,
  consultantssocialMediaMarketing.map,
  consultantswebDesignDevelopment.map,
  consultantswebsiteMaintenance.map,
  doctorsClinicsasoServices.map,
  doctorsClinics360DigitalMarketing.map,
  doctorsClinicsecommerceMarketing.map,
  doctorsClinicsgmbServices.map,
  doctorsClinicsgoogleAds.map,
  doctorsClinicsleadsGeneration.map,
  doctorsClinicslocalSeo.map,
  // doctorsClinicsmarketingAutomation.map,
  doctorsClinicsmetaAds.map,
  doctorsClinicsmobileAppsDevelopment.map,
  doctorsClinicsotherAds.map,
  doctorsClinicsseoServices.map,
  doctorsClinicssocialMediaMarketing.map,
  doctorsClinicswebDesignDevelopment.map,
  doctorsClinicswebsiteMaintenance.map,
  eCommerceBrandsasoServices.map,
  eCommerceBrands360DigitalMarketing.map,
  eCommerceBrandsecommerceMarketing.map,
  eCommerceBrandsgmbServices.map,
  eCommerceBrandsgoogleAds.map,
  eCommerceBrandsleadsGeneration.map,
  eCommerceBrandslocalSeo.map,
  // eCommerceBrandsmarketingAutomation.map,
  eCommerceBrandsmetaAds.map,
  eCommerceBrandsmobileAppsDevelopment.map,
  eCommerceBrandsotherAds.map,
  eCommerceBrandsseoServices.map,
  eCommerceBrandssocialMediaMarketing.map,
  eCommerceBrandswebDesignDevelopment.map,
  eCommerceBrandswebsiteMaintenance.map,
  educationalInstitutionsasoServices.map,
  educationalInstitutions360DigitalMarketing.map,
  educationalInstitutionsecommerceMarketing.map,
  educationalInstitutionsgmbServices.map,
  educationalInstitutionsgoogleAds.map,
  educationalInstitutionsleadsGeneration.map,
  educationalInstitutionslocalSeo.map,
  // educationalInstitutionsmarketingAutomation.map,
  educationalInstitutionsmetaAds.map,
  educationalInstitutionsmobileAppsDevelopment.map,
  educationalInstitutionsotherAds.map,
  educationalInstitutionsseoServices.map,
  educationalInstitutionssocialMediaMarketing.map,
  educationalInstitutionswebDesignDevelopment.map,
  educationalInstitutionswebsiteMaintenance.map,
  fashionBrandsasoServices.map,
  fashionBrands360DigitalMarketing.map,
  fashionBrandsecommerceMarketing.map,
  fashionBrandsgmbServices.map,
  fashionBrandsgoogleAds.map,
  fashionBrandsleadsGeneration.map,
  fashionBrandslocalSeo.map,
  // fashionBrandsmarketingAutomation.map,
  fashionBrandsmetaAds.map,
  fashionBrandsmobileAppsDevelopment.map,
  fashionBrandsotherAds.map,
  fashionBrandsseoServices.map,
  fashionBrandssocialMediaMarketing.map,
  fashionBrandswebDesignDevelopment.map,
  fashionBrandswebsiteMaintenance.map,
  gymsFitnessasoServices.map,
  gymsFitness360DigitalMarketing.map,
  gymsFitnessecommerceMarketing.map,
  gymsFitnessgmbServices.map,
  gymsFitnessgoogleAds.map,
  gymsFitnessleadsGeneration.map,
  gymsFitnesslocalSeo.map,
  // gymsFitnessmarketingAutomation.map,
  gymsFitnessmetaAds.map,
  gymsFitnessmobileAppsDevelopment.map,
  gymsFitnessotherAds.map,
  gymsFitnessseoServices.map,
  gymsFitnesssocialMediaMarketing.map,
  gymsFitnesswebDesignDevelopment.map,
  gymsFitnesswebsiteMaintenance.map,
  hotelResortsasoServices.map,
  hotelResorts360DigitalMarketing.map,
  hotelResortsecommerceMarketing.map,
  hotelResortsgmbServices.map,
  hotelResortsgoogleAds.map,
  hotelResortsleadsGeneration.map,
  hotelResortslocalSeo.map,
  // hotelResortsmarketingAutomation.map,
  hotelResortsmetaAds.map,
  hotelResortsmobileAppsDevelopment.map,
  hotelResortsotherAds.map,
  hotelResortsseoServices.map,
  hotelResortssocialMediaMarketing.map,
  hotelResortswebDesignDevelopment.map,
  hotelResortswebsiteMaintenance.map,
  interiorDesignersasoServices.map,
  interiorDesigners360DigitalMarketing.map,
  interiorDesignersecommerceMarketing.map,
  interiorDesignersgmbServices.map,
  interiorDesignersgoogleAds.map,
  interiorDesignersleadsGeneration.map,
  interiorDesignerslocalSeo.map,
  // interiorDesignersmarketingAutomation.map,
  interiorDesignersmetaAds.map,
  interiorDesignersmobileAppsDevelopment.map,
  interiorDesignersotherAds.map,
  interiorDesignersseoServices.map,
  interiorDesignerssocialMediaMarketing.map,
  interiorDesignerswebDesignDevelopment.map,
  interiorDesignerswebsiteMaintenance.map,
  localBusinessesasoServices.map,
  localBusinesses360DigitalMarketing.map,
  localBusinessesecommerceMarketing.map,
  localBusinessesgmbServices.map,
  localBusinessesgoogleAds.map,
  localBusinessesleadsGeneration.map,
  localBusinesseslocalSeo.map,
  // localBusinessesmarketingAutomation.map,
  localBusinessesmetaAds.map,
  localBusinessesmobileAppsDevelopment.map,
  localBusinessesotherAds.map,
  localBusinessesseoServices.map,
  localBusinessessocialMediaMarketing.map,
  localBusinesseswebDesignDevelopment.map,
  localBusinesseswebsiteMaintenance.map,
  pharmaCompaniesasoServices.map,
  pharmaCompanies360DigitalMarketing.map,
  pharmaCompaniesecommerceMarketing.map,
  pharmaCompaniesgmbServices.map,
  pharmaCompaniesgoogleAds.map,
  pharmaCompaniesleadsGeneration.map,
  pharmaCompanieslocalSeo.map,
  // pharmaCompaniesmarketingAutomation.map,
  pharmaCompaniesmetaAds.map,
  pharmaCompaniesmobileAppsDevelopment.map,
  pharmaCompaniesotherAds.map,
  pharmaCompaniesseoServices.map,
  pharmaCompaniessocialMediaMarketing.map,
  pharmaCompanieswebDesignDevelopment.map,
  pharmaCompanieswebsiteMaintenance.map,
  realEstateasoServices.map,
  realEstate360DigitalMarketing.map,
  realEstateecommerceMarketing.map,
  realEstategmbServices.map,
  realEstategoogleAds.map,
  realEstateleadsGeneration.map,
  realEstatelocalSeo.map,
  // realEstatemarketingAutomation.map,
  realEstatemetaAds.map,
  realEstatemobileAppsDevelopment.map,
  realEstateotherAds.map,
  realEstateseoServices.map,
  realEstatesocialMediaMarketing.map,
  realEstatewebDesignDevelopment.map,
  realEstatewebsiteMaintenance.map,
  restaurantsCafesasoServices.map,
  restaurantsCafes360DigitalMarketing.map,
  // restaurantsCafesecommerceMarketing.map,
  restaurantsCafesgmbServices.map,
  restaurantsCafesgoogleAds.map,
  restaurantsCafesleadsGeneration.map,
  restaurantsCafeslocalSeo.map,
  // restaurantsCafesmarketingAutomation.map,
  restaurantsCafesmetaAds.map,
  restaurantsCafesmobileAppsDevelopment.map,
  restaurantsCafesotherAds.map,
  restaurantsCafesseoServices.map,
  restaurantsCafessocialMediaMarketing.map,
  restaurantsCafeswebDesignDevelopment.map,
  restaurantsCafeswebsiteMaintenance.map,
  startupsEntrepreneursasoServices.map,
  startupsEntrepreneurs360DigitalMarketing.map,
  // startupsEntrepreneursecommerceMarketing.map,
  startupsEntrepreneursgmbServices.map,
  startupsEntrepreneursgoogleAds.map,
  startupsEntrepreneursleadsGeneration.map,
  startupsEntrepreneurslocalSeo.map,
  // startupsEntrepreneursmarketingAutomation.map,
  startupsEntrepreneursmetaAds.map,
  startupsEntrepreneursmobileAppsDevelopment.map,
  startupsEntrepreneursotherAds.map,
  startupsEntrepreneursseoServices.map,
  startupsEntrepreneurssocialMediaMarketing.map,
  startupsEntrepreneurswebDesignDevelopment.map,
  startupsEntrepreneurswebsiteMaintenance.map,
  travelTourismasoServices.map,
  travelTourism360DigitalMarketing.map,
  // travelTourismecommerceMarketing.map,
  travelTourismgmbServices.map,
  travelTourismgoogleAds.map,
  travelTourismleadsGeneration.map,
  travelTourismlocalSeo.map,
  // travelTourismmarketingAutomation.map,
  travelTourismmetaAds.map,
  travelTourismmobileAppsDevelopment.map,
  travelTourismotherAds.map,
  travelTourismseoServices.map,
  travelTourismsocialMediaMarketing.map,
  travelTourismwebDesignDevelopment.map,
  travelTourismwebsiteMaintenance.map
];

export const getMap = (service: string, business: string): ServiceBusinessMap | undefined =>
  maps.find(m => m.service === service && m.business === business);

export const getAllMaps = (): ServiceBusinessMap[] => maps;
