name: Recommit as Owner for Vercel

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  recommit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git as repo owner
        run: |
          git config user.name "Keshav Kumar | <DeveloperKeshavKumar>"
          git config user.email "digiaerotech@gmail.com"

      - name: Recommit latest changes as owner
        run: |
          git commit --amend --no-edit --reset-author || echo "No changes to amend"
          git push origin HEAD:main --force
